#!/bin/bash

export LD_PRELOAD=
export LD_LIBRARY_PATH=
export HOME=/Users/root
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local
export XDG_RUNTIME_DIR=${HOME}/.cache
#mount /proc
#mount /sys
#mount /dev/pts
#mount /dev/shm

export PATH=/bin
#eval `dbus-launch --sh-syntax --exit-with-session`
#echo "DBUS_SESSION_BUS_PID=$DBUS_SESSION_BUS_PID"
echo "startuję $*"
tty

/bin/bash -c "$*"

#kill -9  $DBUS_SESSION_BUS_PID

#umount /dev/shm
#umount /dev/pts
#umount /sys
#umount /proc



