#!/bin/sh

# Source debug definitions
if [ -f ~/.sugar/debug ]; then
        . ~/.sugar/debug
fi
 export OPCODEDIR=/kanapi_packages/Csound-5.8/lib/csound/plugins
 export CSSTRNGS=/kanapi_packages/Csound-5.8/share/csound/xmg

# Start emulator
python -c "import sys; from jarabe.util import emulator; sys.argv[0]='$0'; emulator.main()" "$@"
