#!/bin/bash

. version

if [ ! -f sbs-docker-${VER}.tar.xz ]
then
	wget http://downloads.sourceforge.net/project/kanapi/images/v${VER}/sbs-docker-${VER}.tar.xz
fi
docker build -t kanapi/kanapi-${NAME}:${VER} .

