#!/bin/bash 

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/kanapi_packages/SDL_mixer-1.2.12/lib:\
/kanapi_packages/SDL_ttf-2.0.11/lib:\
/kanapi_packages/SDL_Pango-0.1.2/lib:\
/kanapi_packages/SDL_image-1.2.12/lib:\
/kanapi_packages/librsvg-2.36.4/lib:\
/kanapi_packages/libpaper-1.1.24+nmu2/lib:\
/kanapi_packages/libpng-1.4.12/lib:\
/kanapi_packages/fribidi-0.19.5/lib

/kanapi_packages/tuxpaint-0.9.21/bin/tuxpaint.bin $*
