#!/bin/bash
#
#  Copyright (c) 2012 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts
export USER=root
export HOME=/root

ln -s /kanapi_packages/font-util-1.3.0/share/fonts /root/.fonts
export LD_LIBRARY_PATH=/kanapi_packages/libs

/kanapi_packages/udev-182/libexec/udev/udevd --daemon
rm -f /kanapi_packages/dbus-1.6.8/var/run/dbus/pid
dbus-daemon --system

modprobe -d /kanapi_packages/linux-3.5.3/ iwl4965

wpa_supplicant -B -Dwext -iwlan0 -c /kanapi_packages/wpa_supplicant-1.1/etc/wifi.conf
dhclient wlan0 -cf /kanapi_packages/dhcp-4.2.4-P2/etc/dhclient.conf

/bin/bash

