#!/bin/bash

. version

docker tag kanapi-${NAME}:ci kanapi/kanapi-${NAME}:${VER}
docker tag kanapi/kanapi-${NAME}:${VER} kanapi/kanapi-${NAME}:latest
docker push kanapi/kanapi-${NAME}:${VER}
docker push kanapi/kanapi-${NAME}:latest
