all: sbs_docker bbs_docker cli_docker

sbs_docker:
	pushd ../kanapi_system/docker/sbs; ./make_image; popd

cli_docker:
	pushd cli; ./make_image; popd

bbs_docker:
	pushd bbs; ./make_image; popd

test:
	echo "tests disabled"

