all: bbs_sbs core_cli

bbs_sbs:
	chroot ../sbs-`uname -m` /_start_bbs_build

core_cli:
	bash -c "export PKG_COMMAND=cli; chroot ../sbs-`uname -m` /_start_install"

bbs: check_links
	cd ../kanapi_system/`uname -m`   ; make gettext ACTION=install
	cd ../kanapi_system/`uname -m`   ; make pkg-config ACTION=install
	cd ../kanapi_system/`uname -m`   ; make bbs ACTION=install

check_links:
	./prepare_links

test:
	echo "tests disabled"

busybox:	
	cd ../kanapi_system/`uname -m`   ; make busybox	 ACTION=install V=1

