all: b_0_10

b_0_10:
	echo "build disabled on branch 0.10"

bbs: check_links
	cd ../kanapi_system/`uname -m`   ; make pkg-config ACTION=install
	cd ../kanapi_system/`uname -m`   ; make bbs	 ACTION=install

cli:	
	cd ../kanapi_system/`uname -m`   ; make cli	 ACTION=install

check_links:
	./prepare_links

test:
	echo "tests disabled"

busybox:	
	cd ../kanapi_system/`uname -m`   ; make busybox	 ACTION=install VERBOSE=1

