all: 
	chroot ../sbs-`uname -m` /_start_build

test: 
	chroot ../sbs-`uname -m` /_start_chroot

test-sbs: 
	chroot ../sbs-`uname -m` /_test_build

bbs: 
	chroot ../sbs-`uname -m` /_start_bbs_build

#PKG_COMMAND contains target to rebuild
rebuild: 
	chroot ../sbs-`uname -m` /_start_rebuild

install: 
	chroot ../sbs-`uname -m` /_start_install

