all: bbs

bbs: check_links
	PATH=$${PATH}:/root/bin; cd ../kanapi_system/`uname -m`   ; make pkg-config ACTION=install
	PATH=$${PATH}:/root/bin; cd ../kanapi_system/`uname -m`   ; make bbs	 ACTION=install

cli:	
	cd ../kanapi_system/`uname -m`   ; make cli	 ACTION=install VERBOSE=1

check_links:
	./prepare_links

test:
	echo "tests disabled"

