all: 
	chroot ../sbs-`uname -m` /_start_build

test: 
	chroot ../sbs-`uname -m` /_start_chroot

include:
	chroot ../sbs-`uname -m` /bin/update_include

bbs_sbs:
	chroot ../sbs-`uname -m` /_start_bbs_build

