all: bbs cli

bbs: check_travis
	cd ../kanapi_system/`uname -m`   ; make pkg-config ACTION=install
	cd ../kanapi_system/`uname -m`   ; make bbs	 ACTION=install

cli:	
	cd ../kanapi_system/`uname -m`   ; make cli	 ACTION=install

bbs_sbs:
	sudo chroot ../sbs-`uname -m` /_start_bbs_build

cross_compilers:
	cd ../cross_compilers/`uname -m` ; make gcc ACTION=install
	cd ../kanapi_system/`uname -m`   ; make cross_gcc ACTION=install

travis_test: check_travis
	cd ../kanapi_system/`uname -m`   ; make pkg-config ACTION=install
	cd ../kanapi_system/`uname -m`   ; make openssl	 ACTION=install
	cd ../kanapi_system/`uname -m`   ; make git	 ACTION=install
	cd ../kanapi_system/`uname -m`   ; make coreutils	 ACTION=install

check_travis:
	./prepare_links

apps_txt: check_travis
	cd ../kanapi_system/`uname -m`   ; make apps_txt ACTION=install

devel: check_travis
	cd ../kanapi_system/`uname -m`   ; make devel ACTION=install

sound: check_travis
	cd ../kanapi_system/`uname -m`   ; make sound ACTION=install

x-support: cross_compilers
	cd ../kanapi_system/`uname -m`   ; make pkg-config ACTION=install
	cd ../kanapi_system/`uname -m`   ; make ncurses ACTION=install
	cd ../kanapi_system/`uname -m`   ; make cmake ACTION=install
	cd ../kanapi_system/`uname -m`   ; make Python ACTION=install
	cd ../kanapi_system/`uname -m`   ; make ninja ACTION=install
	cd ../kanapi_system/`uname -m`   ; make perl ACTION=install
	cd ../kanapi_system/`uname -m`   ; make util-linux ACTION=install
	cd ../kanapi_system/`uname -m`   ; make x-support ACTION=install

test:
	echo "tests disabled"

test_cross_compilers:
	cd ../cross_compilers/`uname -m` ; make gcc ACTION=test
	cd ../kanapi_system/`uname -m` ; make cross_gcc ACTION=test

vim: check_travis
	cd ../kanapi_system/`uname -m`   ; make vim	 ACTION=install V=1
