#!/bin/bash
#
# Copyright (c) 2012-2013 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.


export CXXFLAGS="-O3 -ffast-math `pkg-config --libs gl x11 xext xcursor xxf86vm` -ldl -lrt -lpthread"

for i in [012]* Demo
do	
	echo $i
	cd $i
	make CXXFLAGS="${CXXFLAGS}"
	cd ..
done
