#!/bin/bash

if [ ! -d packages ] ; then mkdir packages ; fi
if [ ! -d kanapi ] ; then git clone https://github.com/jdanecki/kanapi.git kanapi ; fi

ID=`docker ps -a --filter "name=kanapi" -q`
docker start -i -a ${ID}

