#!/bin/bash
#
#  Copyright (c) 2012 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

rm -rf initrd_fs
mkdir -p initrd_fs/kanapi_packages
mkdir initrd_fs/sys
mkdir initrd_fs/mnt

for d in bin dev etc proc root tmp usr
do
	cp -ar ../kanapi_base_system/kanapi_system/$d initrd_fs
done

for d in bash-4.2.20/bin \
	eglibc-20133/bin eglibc-20133/etc eglibc-20133/lib \
	coreutils-8.19/bin \
	util-linux-2.22/bin util-linux-2.22/lib
do
	mkdir -p initrd_fs/kanapi_packages/$d
	cp -ar ../kanapi_base_system/kanapi_system/kanapi_packages/$d/* initrd_fs/kanapi_packages/$d
done

cp boot/init initrd_fs
cd initrd_fs
find . -print | cpio -o -Hnewc > ../boot/initrd
cd ..
