#!/bin/bash
#
# Copyright (c) 2012-2014 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

#$1 package name
#$2 package version
#$3 package url

mkdir $1
cat TEMPLATE/packagename-version.compile | sed "s/^PACKAGE_NAME=/PACKAGE_NAME=$1/" | sed "s/^VER=/VER=$2/" > $1/$1-$2.compile
cat TEMPLATE/prepare | sed "s/^PACKAGE_NAME=/PACKAGE_NAME=$1/" | sed "s/^VER=/VER=$2/" | sed "s@^# http://@# $3@" > $1/prepare-$2
chmod +x $1/$1-$2.compile
chmod +x $1/prepare-$2

