#!/bin/bash
#
# Copyright (c) 2012-2014 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

ln -s  /kanapi_packages/libfm-1.1.0/lib/libfm-gtk.so.3* /kanapi_packages/libs
ln -s  /kanapi_packages/libfm-1.1.0/lib/libfm.so* /kanapi_packages/libs
ln -s  /kanapi_packages/gtk+-2.24.13/lib/libgtk-x11-2.0.* /kanapi_packages/libs
ln -s  /kanapi_packages/gtk+-2.24.13/lib/libgdk-x11-2.0.* /kanapi_packages/libs
ln -s  /kanapi_packages/atk-2.4.0/lib/libatk-1.0.* /kanapi_packages/libs
ln -s  /kanapi_packages/glib-2.32.4/lib/libg* /kanapi_packages/libs
ln -s  /kanapi_packages/pango-1.30.1/lib/libpango* /kanapi_packages/libs
ln -s  /kanapi_packages/cairo-1.12.4/lib/libcairo* /kanapi_packages/libs
ln -s  /kanapi_packages/fontconfig-2.10.1/lib/libfontconfig.* /kanapi_packages/libs
ln -s  /kanapi_packages/freetype-2.4.10/lib/libfreetype.* /kanapi_packages/libs/
ln -s  /kanapi_packages/gdk-pixbuf-2.26.4/lib/libgdk_pixbuf-2.0.* /kanapi_packages/libs
ln -s /kanapi_packages/expat-2.1.0/lib/libexpat.* /kanapi_packages/libs
ln -s /kanapi_packages/libXcursor-1.1.13/lib/libXcursor.* /kanapi_packages/libs
ln -s /kanapi_packages/Mesa-8.0.4/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/zlib-1.2.7/lib/libz*  /kanapi_packages/libs
ln -s /kanapi_packages/libxcb-1.8.1/lib/libxcb*  /kanapi_packages/libs
ln -s /kanapi_packages/libdrm-2.4.39/lib/libdrm*   /kanapi_packages/libs
ln -s /kanapi_packages/libXfixes-5.0/lib/lib*   /kanapi_packages/libs
ln -s /kanapi_packages/libXdamage-1.1.3/lib/lib*   /kanapi_packages/libs
ln -s /kanapi_packages/wireless_tools-29/lib/libiw.so* /kanapi_packages/libs
ln -s /kanapi_packages/nss-3.14/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/libnl-3.2.16/lib/libnl* /kanapi_packages/libs
ln -s /kanapi_packages/dbus-1.6.8/lib/libdbus-1.* /kanapi_packages/libs/
ln -s /kanapi_packages/libXaw3dXft-1.6.2/lib/libXaw3d.* /kanapi_packages/libs
ln -s /kanapi_packages/libXft-2.3.1/lib/libXft.*  /kanapi_packages/libs
ln -s  /kanapi_packages/libpng-1.5.13/lib/libpng* /kanapi_packages/libs
ln -s  /kanapi_packages/tiff-4.0.3/lib/libtiff*  /kanapi_packages/libs
ln -s /kanapi_packages/jpeg-8d/lib/libjpeg.* /kanapi_packages/libs
ln -s /kanapi_packages/libelf-0.8.13/lib/libelf.* /kanapi_packages/libs/
ln -s /kanapi_packages/alsa-lib-1.0.25/lib/libasound.* /kanapi_packages/libs
ln -s /kanapi_packages/ncurses-5.9/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/libXfont-1.4.5/lib/libXfont.* /kanapi_packages/libs
ln -s /kanapi_packages/SDL_mixer-1.2.12/lib/libSDL_mixer* /kanapi_packages/libs
ln -s /kanapi_packages/SDL_image-1.2.12/lib/libSDL_image*  /kanapi_packages/libs
ln -s /kanapi_packages/SDL_gfx-2.0.24/lib/libSDL_gfx.*  /kanapi_packages/libs
ln -s /kanapi_packages/SDL_ttf-2.0.11/lib/libSDL_ttf*  /kanapi_packages/lib
ln -s /kanapi_packages/readline-6.2/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/libxslt-1.1.27/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/libvorbis-1.3.3/lib/libvorbis* /kanapi_packages/libs
ln -s /kanapi_packages/libogg-1.3.0/lib/libogg.* /kanapi_packages/libs
ln -s /kanapi_packages/libmad-0.15.1b/lib/libmad.* /kanapi_packages/libs
ln -s /kanapi_packages/libXrender-0.9.7/lib/libXrender.* /kanapi_packages/libs
ln -s /kanapi_packages/fribidi-0.19.5/lib/libfribidi.* /kanapi_packages/libs
ln -s /kanapi_packages/libsoup-2.38.1/lib/libsoup-2.4.* /kanapi_packages/libs
ln -s /kanapi_packages/icu4c-50_1_1/lib/libicu* /kanapi_packages/libs
ln -s /kanapi_packages/librsvg-2.36.4/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/SDL_net-1.2.8/lib/libSDL_net* /kanapi_packages/libs
ln -s /kanapi_packages/t4k_common-0.1.1/lib/libt4k_common.* /kanapi_packages/libs
ln -s /kanapi_packages/SDL_Pango-0.1.2/lib/libSDL_Pango.* /kanapi_packages/libs
ln -s /kanapi_packages/webkitgtk-1.10.2/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/gstreamer-0.10.36/lib/libgst* /kanapi_packages/libs
ln -s /kanapi_packages/udev-175/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/nettle-2.5/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/libXi-1.6.1/lib/libXi.* /kanapi_packages/libs
ln -s /kanapi_packages/libmikmod-3.2.0/lib/libmikmod.* /kanapi_packages/libs
ln -s /kanapi_packages/libXrandr-1.3.2/lib/libXrandr.* /kanapi_packages/libs
ln -s /kanapi_packages/openssl-1.0.1c/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/dbus-glib-0.100/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/util-linux-2.22/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/portaudio-v19_20111121/lib/libportaudio* /kanapi_packages/libs
ln -s /kanapi_packages/espeak-1.46.02-source/lib/libespeak.* /kanapi_packages/libs
ln -s /kanapi_packages/physfs-2.0.3/lib/libphysfs.* /kanapi_packages/libs
ln -s /kanapi_packages/curl-7.28.1/lib/libcurl.* /kanapi_packages/libs
ln -s /kanapi_packages/SDL-1.2.15/lib/libSDL* /kanapi_packages/libs
ln -s /kanapi_packages/openal-soft-1.15.1/lib/libopenal.so* /kanapi_packages/libs
ln -s /kanapi_packages/glew-1.9.0/lib/libGLEW.* /kanapi_packages/libs
ln -s /kanapi_packages/allegro-5.0.8/lib/liballegro* /kanapi_packages/libs
ln -s /kanapi_packages/glibmm-2.28.2/lib/libg* /kanapi_packages/libs
ln -sf /kanapi_packages/libsigc++-2.3.1/lib/libsigc-2.0.* /kanapi_packages/libs
ln -s /kanapi_packages/boost-1_52_0/lib/libboost_* /kanapi_packages/libs
ln -s /kanapi_packages/xz-5.0.4/lib/liblzma.* /kanapi_packages/libs
ln -s /kanapi_packages/rtmpdump-2.3/lib/librtmp.*  /kanapi_packages/libs
ln -s /kanapi_packages/pcre-8.32/lib/libpcre*   /kanapi_packages/libs
ln -s /kanapi_packages/libxml2-2.9.0/lib/libxml2.*   /kanapi_packages/libs
ln -s /kanapi_packages/libxml++-2.33.2/lib/libxml++-2.6*   /kanapi_packages/libs
ln -s /kanapi_packages/yaml-0.1.4/lib/libyaml* /kanapi_packages/libs
ln -s /kanapi_packages/wxPython-src-2.8.12.1/lib/libwx_* /kanapi_packages/libs
ln -s /kanapi_packages/gnutls-3.1.6/lib/libgnutls* /kanapi_packages/libs
ln -s /kanapi_packages/pixman-0.26.2/lib/libpixman-1.* /kanapi_packages/libs
ln -s /kanapi_packages/libXtst-1.2.1/lib/libXtst.* /kanapi_packages/libs
ln -s /kanapi_packages/libXcomposite-0.4.3/lib/libXcomposite.*  /kanapi_packages/libs
ln -s /kanapi_packages/GConf-2.32.4/lib/libgconf-2.* /kanapi_packages/libs
ln -s /kanapi_packages/openjpeg-1.5.1/lib/libopenjpeg.so* /kanapi_packages/libs
ln -s /kanapi_packages/libwnck-2.31.0/lib/libwnck-1.* /kanapi_packages/libs
ln -s  /kanapi_packages/popt-1.14/lib/libpopt.* /kanapi_packages/libs
ln -s /kanapi_packages/libXinerama-1.1.2/lib/libXinerama.* /kanapi_packages/libs
ln -s /kanapi_packages/libXxf86vm-1.1.2/lib/libXxf86vm.* /kanapi_packages/libs
ln -s /kanapi_packages/libgnome-2.32.1/lib/libgnome-2.* /kanapi_packages/libs
ln -s /kanapi_packages/libbonobo-2.32.1/lib/libbonobo-* /kanapi_packages/libs
ln -s /kanapi_packages/flac-1.2.1/lib/libFLAC* /kanapi_packages/libs
ln -s /kanapi_packages/libsndfile-1.0.25/lib/libsndfile.* /kanapi_packages/libs
ln -s /kanapi_packages/Csound-5.8/lib/libcs* /kanapi_packages/libs
ln -s /kanapi_packages/fluidsynth-1.1.1/lib/libfluidsynth.* /kanapi_packages/libs
ln -s /kanapi_packages/tk-8.6.0/lib/libtk* /kanapi_packages/libs
ln -s /kanapi_packages/Csound-5.19.01/lib/libcsound.so.5.2 /kanapi_packages/libs
ln -s /kanapi_packages/Csound-5.19.01/lib/libcsnd.so.5.2  /kanapi_packages/libs
ln -s /kanapi_packages/gst-plugins-bad-0.10.23/lib/libgst* /kanapi_packages/libs
ln -s /kanapi_packages/x264-snapshot-20130218-2245/lib/libx264.so* /kanapi_packages/libs
ln -s /kanapi_packages/libva-1.1.0/lib/libva* /kanapi_packages/libs
ln -s /kanapi_packages/libav-0.8.4/lib/lib* /kanapi_packages/libs
ln -s /kanapi_packages/faac-1.28/lib/libfaac.* /kanapi_packages/libs
ln -s /kanapi_packages/phonon-4.6.0/lib/libphononexperimental.so* /kanapi_packages/libs
ln -s /kanapi_packages/poppler-0.22.0/lib/libpoppler* /kanapi_packages/libs
ln -s /kanapi_packages/gtksourceview-2.10.5/lib/libgtksourceview-2.0.* /kanapi_packages/libs
ln -s /kanapi_packages/Python-2.7.3/lib/libpython2.7.* /kanapi_packages/libs
ln -s /kanapi_packages/goocanvas-1.0.0/lib/libgoocanvas.* /kanapi_packages/libs
ln -s /kanapi_packages/tcl-8.6.0/lib/libtcl* /kanapi_packages/libs

