#!/bin/bash
#
# Copyright (c) 2012 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

ln -s  /kanapi_packages/libfm-1.1.0/lib/libfm-gtk.so.3* /kanapi_packages/libs
ln -s  /kanapi_packages/libfm-1.1.0/lib/libfm.so* /kanapi_packages/libs
ln -s  /kanapi_packages/gtk+-2.24.13/lib/libgtk-x11-2.0.* /kanapi_packages/libs
ln -s  /kanapi_packages/gtk+-2.24.13/lib/libgdk-x11-2.0.* /kanapi_packages/libs
ln -s  /kanapi_packages/atk-2.4.0/lib/libatk-1.0.* /kanapi_packages/libs
ln -s  /kanapi_packages/glib-2.32.4/lib/libg* /kanapi_packages/libs
ln -s  /kanapi_packages/pango-1.30.1/lib/libpango* /kanapi_packages/libs
ln -s  /kanapi_packages/cairo-1.12.4/lib/libcairo* /kanapi_packages/libs
ln -s  /kanapi_packages/fontconfig-2.10.1/lib/libfontconfig.* /kanapi_packages/libs
ln -s  /kanapi_packages/freetype-2.4.10/lib/libfreetype.* /kanapi_packages/libs/
ln -s  /kanapi_packages/gdk-pixbuf-2.26.4/lib/libgdk_pixbuf-2.0.* /kanapi_packages/libs
ln -s /kanapi_packages/expat-2.1.0/lib/libexpat.* /kanapi_packages/libs
ln -s /kanapi_packages/libXcursor-1.1.13/lib/libXcursor.* /kanapi_packages/libs
ln -s /kanapi_packages/Mesa-8.0.4/lib/lib* /kanapi_packages/libs

