#!/bin/bash
#
#  Copyright (c) 2012 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

echo "Witam w KaNaPi"

mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo "czekam na dysk"
sleep 3

mount -t ext4 /dev/sdb2 -o noatime /kanapi_packages
ln -sfn /kanapi_packages/bin /bin

mount -t devpts devpts /dev/pts
export USER=root
export HOME=/root
export PATH=/bin:.

ln -s /kanapi_packages/font-util-1.3.0/share/fonts /root/.fonts
ln -s /kanapi_packages/xfconf-4.10.0/share/dbus-1/services/org.xfce.Xfconf.service /kanapi_packages/dbus-1.6.8/share/dbus-1/services

export LD_LIBRARY_PATH=/kanapi_packages/libs

/bin/bash

