#!/bin/bash

tar -xJf ../sbs-x86_64.tar.xz

#should be move to SBS
ln -svf /kanapi_build/kanapi/cross_compilers/scripts/pkg_kanapi sbs-x86_64/bin/pkg_kanapi
ln -svf /kanapi_build/kanapi/kanapi_system/scripts/pkg sbs-x86_64/bin/pkg
ln -svf /kanapi_build/kanapi/kanapi_system/scripts/pkg_dev sbs-x86_64/bin/pkg_dev
ln -svf /kanapi_build/kanapi/kanapi_system/scripts/update_include sbs-x86_64/bin/update_include
cp configure sbs-x86_64
mkdir -p sbs-x86_64/kanapi_0.9/x86_64/home/.local
mkdir -p sbs-x86_64/root/src

tar -C sbs-x86_64 -cf sbs-x86_64.tar .
docker build -t kanapi-sbs:1 .

