#!/bin/bash

. version

USE_LOCAL=1
DIR=`pwd`
if [ ! -d ${HOME}/src ] ; then mkdir ${HOME}/src ; fi
if [ ! -d kanapi ] 
then 
	if [ "${USE_LOCAL}" = "1" ] 
	then
	   REPO_BASE=`pwd | sed "s@/kanapi_system/docker/.*/interactive@@"`
		git clone ${REPO_BASE} kanapi
	else
		git clone https://github.com/jdanecki/kanapi.git kanapi
	fi
else
	pushd kanapi
	git pull
	popd
fi

docker create -i -t --name kanapi-${NAME}-${VER} -v ${DIR}/kanapi:/kanapi_build/kanapi -v ${HOME}/src:/kanapi_0.9/x86_64/home/src -v ${HOME}/.ccache:/kanapi_0.9/x86_64/home/.ccache -e HOME=/kanapi_0.9/x86_64/home kanapi/kanapi-${NAME}

