#!/bin/bash

. ./set_variables

LIB=$1
LIBVER=${LIB}_ver
LIBDIR=${KANAPI_BASE}/${LIB}-${!LIBVER}/lib
LIBNAME=lib${LIB}.so

#echo "LIB=${LIB}"
#echo "LIBVER=${LIBVER}"
#echo "LIBDIR=${LIBDIR}"
#echo "LIBNAME=${LIBNAME}"

file -L ${LIBDIR}/${LIBNAME}
ldd ${LIBDIR}/${LIBNAME}

