#!/bin/bash

git clone https://github.com/jdanecki/kanapi.git kanapi
cd kanapi ; git show; cd ..

if [ "${SHIPPABLE}" = "true" -o  "${TRAVIS}" = "true" ]
then
	docker build -f Dockerfile-travis -t kanapi-bbs:ci --no-cache .
else
	docker build -t kanapi-bbs:ci --no-cache .
fi
