#!/bin/bash

git clone ../../../kanapi kanapi

if [ "${SHIPPABLE}" = "true" -o  "${TRAVIS}" = "true" ]
then
	docker build -f Dockerfile-travis -t kanapi-bbs:ci --no-cache .
else
	docker build -t kanapi-bbs:ci --no-cache .
fi
