FROM kanapi/kanapi-sbs
MAINTAINER Jacek Danecki <jacek.m.danecki@gmail.com>
RUN mkdir /kanapi_build/kanapi
COPY kanapi /kanapi_build/kanapi
RUN mkdir -p ${HOME}/src; cd /kanapi_build/kanapi/kanapi_system/kanapi-bbs ; ./install all-sbs verbose
CMD ["/bin/bash"]
