FROM kanapi/kanapi-BASE_IMAGE
MAINTAINER Jacek Danecki <jacek.m.danecki@gmail.com>
ENV HOME=/kanapi_0.10/home
RUN mkdir /kanapi_build/kanapi
COPY kanapi /kanapi_build/kanapi
ENV SHIPPABLE="true"
ENV CI="true"
RUN mkdir -p ${HOME}/ci_src; cd /kanapi_build/kanapi/kanapi_system/kanapi-bbs; ./install all-sbs
CMD ["/bin/bash"]
