#!/bin/bash

USE_LOCAL=1

. version

REPO_BASE=`git rev-parse --show-toplevel`

if [ ! -d kanapi ] 
then 
	if [ "${USE_LOCAL}" = "1" ] 
	then 
		git clone ${REPO_BASE} kanapi
	else
		git clone https://github.com/jdanecki/kanapi.git kanapi
	fi
else
	pushd kanapi
	git pull
	popd
fi
cat Dockerfile.template | sed "s/BASE_IMAGE/${BASE_IMAGE}/" > Dockerfile.shippable
docker build -f Dockerfile.shippable -t kanapi-${NAME}:${VER} .
