#!/bin/bash

if [ "${SHIPPABLE}" = "true" -o  "${TRAVIS}" = "true" ]
then
	docker build -f Dockerfile-gtk-travis -m 4g -t kanapi-apps-gtk:ci .
else
	docker build -f Dockerfile-gtk -m 4g -t kanapi-apps-gtk:ci .
fi

