FROM kanapi/kanapi-gtk
MAINTAINER Jacek Danecki <jacek.m.danecki@gmail.com>
COPY kanapi /kanapi_build/kanapi
ENV TRAVIS="true"
ENV CI="true"
RUN mkdir -p ${HOME}/ci_src; /kanapi_build/kanapi/kanapi_system/docker/configure; cd /kanapi_build/kanapi/kanapi_system/x86_64 && ./install apps-gtk
CMD ["/bin/bash"]
