#!/bin/bash
#
#  Copyright (c) 2012-2016 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

cd /
killall -9 dhclient
killall -9 wpa_supplicant
killall -9 dbus-daemon
killall -9 udevd
sync
sync
sync
mount -o remount,ro /kanapi_packages
mount -o remount,ro /kanapi_packages_x86_64
mount -o remount,ro /kanapi_external
mount -o remount,ro /kanapi_build
umount /kanapi_packages
umount /kanapi_packages_x86_64
umount /kanapi_external
umount /kanapi_build
echo "mozna wylaczyc"
reboot -f

