#!/bin/bash

# $1 - package name
# $2 - verbose

if [ "x$1" == "x" ]
then
	echo "package name missing!"
	echo "use: script_name package_name"
	echo "where script_name is one from download|prepare|configure|build|install|help|rebuild_install|reinstall|redownload|verify|reverify"
	echo "for example: download gzip"
else
	case "x$2" in
		xverbose) make $1 ACTION=`basename $0` V=1
			;;
        xout) make -s $1 ACTION=`basename $0` V=2
			;;
        xci) make -s $1 ACTION=`basename $0` V=3
			;;
		*) make -s $1 ACTION=`basename $0` V=0
			;;
	esac
fi

