ifeq (x$(KANAPI_COMMON_INCLUDED),x)
KANAPI_COMMON_INCLUDED=1

ifeq (x$(KANAPI_TOP),x)
BASE=
else
BASE=$(KANAPI_TOP)/
endif

KANAPI_VER=$(shell cat  $(BASE)../scripts/KANAPI_VER)
KANAPI_BASE=/kanapi_$(KANAPI_VER)/packages

COMPILERS=gcc

include $(BASE)../scripts/config.kanapi
include $(BASE)../scripts/config-Makefile.kanapi
include $(BASE)../scripts/colors.kanapi
include $(BASE)../scripts/rules.kanapi
endif

