#!/bin/bash

cd /kanapi_${KANAPI_VER}/`uname -m`/packages

rm -rf include
mkdir include

for dir in *
do
	if [ -d $dir/include ] ;
	then
		for subdir in $dir/include/*
		do
			if [ -d $subdir ]
			then
				if [ ! -d include/`basename $subdir` ] ; then mkdir include/`basename $subdir` ; fi
				#echo "dir: $dir $subdir"
				ln -svf `pwd`/$subdir/* include/`basename $subdir`
			else
				ln -svf `pwd`/$subdir include
				#echo "file: $subdir"
			fi
		done
	fi
done
