#!/bin/bash

KANAPI_VER=0.9

cd /kanapi_${KANAPI_VER}/`uname -m`/packages

rm -rf include
mkdir include

search_in_dir() {
	if [ -d $2 ]
	then
			name=`echo $2 | sed "s@$1\/@@"` 
	  	#	echo "dir: $1 --- $2 -> $name"
			if [ ! -d $name ] ; then mkdir -p $name ; fi
			for f in $2/*
			do
				search_in_dir $1 $f
			done
	else
			name=`echo $2 | sed "s@$1\/@@"` 
		#	echo "fil: $1 --- $2 -> $name"
			ln -sf $2 $name
	 fi
}

search_include_dir() {
		 for package in $1/*
		 do
		 		echo "looking in $package"
				if [ -d $package/include ] 
				then
					for fd in $package/include/*
					do
					  search_in_dir $package $fd
					done
			  fi
		 done
}


search_include_dir `pwd`

