#!/bin/bash
#
# Copyright (c) 2012 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

#LIBC_PREFIX=/kanapi_packages/eglibc-20133
MPC_PREFIX=/kanapi_packages/mpc-1.0
GMP_PREFIX=/kanapi_packages/gmp-10.0.1
MPFR_PREFIX=/kanapi_packages/mpfr-4.1.0

export LD_LIBRARY_PATH=$MPFR_PREFIX/lib/:$GMP_PREFIX/lib:$MPC_PREFIX/lib

#export LIBRARY_PATH=$LIBC_PREFIX/lib
#export LDFLAGS=-Wl,-dynamic-linker=$LIBRARY_PATH/ld-linux.so.2
#export CPPFLAGS=-I$LIBC_PREFIX/include
export CC="gcc -mtune=native -U_FORTIFY_SOURCE -O2"
#-I$LIBC_PREFIX/include
export PATH=/kanapi_packages/binutils-2.22.51.20120122/bin:/kanapi_packages/binutils-2.22.51.20120122/i686-kanapi-linux/bin:/kanapi_packages/gcc-4.7.0/bin:$PATH

