#!/bin/bash
#
# Copyright (c) 2012 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

rm -rf builds
mkdir builds

for i in packages/*
do
	dpkg-deb -x $i builds
done

echo "root:x:0:0:root:/root:/bin/bash" > builds/etc/passwd
echo "root:x:0:" > builds/etc/group
sudo cp -ar /dev builds/dev
cp /etc/resolv.conf builds/etc
mkdir builds/tmp
mkdir builds/kanapi_packages
mkdir -p builds builds/kanapi_build/src
mkdir -p builds builds/kanapi_build/out

cd builds
 ln -s /usr/bin/cpp lib/cpp
 ln -s /usr/bin/gawk usr/bin/awk
 ln -s /usr/bin/aclocal-1.11 usr/bin/aclocal
 ln -s /usr/bin/automake-1.11 usr/bin/automake
 ln -s /usr/include/i386-linux-gnu/asm usr/include/asm
 ln -s /usr/include/i386-linux-gnu/bits usr/include/bits
 ln -s /usr/include/i386-linux-gnu/sys usr/include/sys
 ln -s /usr/include/i386-linux-gnu/gnu usr/include/gnu
 echo "/kanapi_packages/lib" >> etc/ld.so.conf
cd ..
chroot builds ldconfig

