#!/bin/bash
#
#  Copyright (c) 2012 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

dd if=/dev/zero of=kanapi_image bs=1024 count=512000
losetup /dev/loop0 kanapi_image

echo "Create 2 partitions: first as vfat, second as linux partition\n"

fdisk /dev/loop0
partprobe /dev/loop0

mkfs.vfat -I /dev/loop0p1

syslinux /dev/loop0p1

mount /dev/loop0p1 tmp
cp boot/* tmp
umount tmp
install-mbr -T /dev/loop0 /dev/loop0

