#!/bin/bash
#
#  Copyright (c) 2012-2015 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

PEN=/dev/sdc
PEN_PART=${PEN}1

echo "Create 2 partitions:"
echo "first as vfat (id=b) for syslinux- size about 100MB "
echo "second as linux partition (id=83) - /kanapi_packages"

fdisk $PEN
partx -l $PEN
udevadm settle

mkfs.vfat -I ${PEN_PART}

syslinux ${PEN_PART}

mkdir tmp
mount ${PEN_PART} tmp
cp boot_usb/* tmp
umount tmp
install-mbr -T ${PEN} ${PEN}

