#!/bin/bash
#
#  Copyright (c) 2012-2015 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

cd recovery_fs

find . -print | cpio -o -Hnewc > ../recovery
cd ..
#mount /dev/sdb1 p1
mount /dev/sda1 p1
rm recovery.gz
gzip recovery
cp recovery.gz p1/recovery.gz
umount p1
sync
sync
sync

