#!/bin/bash

USE_LOCAL=1

. version

REPO_BASE=`git rev-parse --show-toplevel`
KANAPI_VER=`cat ${REPO_BASE}/kanapi_system/scripts/KANAPI_VER`

if [ ! -d kanapi ] 
then 
	if [ "${USE_LOCAL}" = "1" ] 
	then 
		git clone ${REPO_BASE} kanapi
	else
		git clone https://github.com/jdanecki/kanapi.git kanapi
	fi
else
	pushd kanapi
	git pull
	popd
fi
cat Dockerfile.template | sed "s/BASE_IMAGE/${BASE_IMAGE}/" > Dockerfile
cat interactive/build.template | sed "s/@KANAPI_VER@/${KANAPI_VER}/" | sed "s/%SBS_BUILD%/${SBS_BUILD}/"  > build
chmod +x build
docker build -t kanapi-${NAME}:${VER} . && rm -rf kanapi
