#!/bin/bash

BUILD_VERSION=0.10

ln -sf /kanapi_build/kanapi/kanapi_system/scripts/pkg_kanapi /bin/pkg_kanapi
mkdir -p /kanapi_${BUILD_VERSION}
ln -sf /kanapi_${BUILD_VERSION}/packages/include /usr/local/include
cd /kanapi_build/kanapi/kanapi_system/kanapi-sbs
./install sbs verbose
