#!/bin/bash
#
#  Copyright (c) 2012-2017 Jacek Danecki <jacek.m.danecki@gmail.com>
#
# This file is part of KaNaPi project
#
# KaNaPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KaNaPi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with KaNaPi.  If not, see <http://www.gnu.org/licenses/>.

set -e

. ../scripts/config.kanapi

ARCH=`uname -m`

export KANAPI_VER=`cat ../scripts/KANAPI_VER`
echo "Preparing SBS for ${KANAPI_VER} on ${ARCH}"
KANAPI_BASE=/kanapi_${KANAPI_VER}/${ARCH}
KANAPI_BASE_PACKAGES=${KANAPI_BASE}/packages
KANAPI_BASE_LOCAL=kanapi_${KANAPI_VER}/${ARCH}
INITRD_DIR=sbs-${ARCH}

echo "KANAPI_BASE=${KANAPI_BASE}"
echo "INITRD_DIR=${INITRD_DIR}"
rm -rf ${INITRD_DIR}
mkdir ${INITRD_DIR}
cd ${INITRD_DIR}

echo "Copying files"
for d in dev proc run sys tmp var
do
	cp -ar ${KANAPI_BASE}/$d .
done

mkdir packages
mkdir etc
mkdir lib

for pkg in bash binutils busybox curl file gcc glib glibc gmp libffi libgcrypt \
	libssh2 make mpc mpfr openssl zlib
do
	pkg_v=${pkg}_ver
	cp -ar ${KANAPI_BASE_PACKAGES}/${pkg}-${!pkg_v} packages
done
cp -ar ${KANAPI_BASE_PACKAGES}/pkg-config-${pkg_config_ver} packages
cp -ar ${KANAPI_BASE_PACKAGES}/linux-headers-${linux_headers_ver} packages
cp -ar ${KANAPI_BASE_PACKAGES}/libgpg-error-${libgpg_error_ver} packages

mkdir -p ${KANAPI_BASE_LOCAL}/home/src
echo "export PS1='sbs:\w\\\$ '" > ${KANAPI_BASE_LOCAL}/home/.bashrc
chmod +x ${KANAPI_BASE_LOCAL}/home/.bashrc
ln -sf .bashrc ${KANAPI_BASE_LOCAL}/home/.bash_profile

ln -sf /packages ${KANAPI_BASE_LOCAL}
ln -sf /bin ${KANAPI_BASE_LOCAL}/bin
mkdir -p ${KANAPI_BASE_LOCAL}/cross/${ARCH}
for pkg in binutils gcc gmp mpc mpfr 
do
	pkg_v=${pkg}_ver
	ln -sf ${KANAPI_BASE_PACKAGES}/${pkg}-${!pkg_v} ${KANAPI_BASE_LOCAL}/cross/${ARCH}
done
ln -sf ${KANAPI_BASE_PACKAGES}/pkg-config-${pkg_config_ver} ${KANAPI_BASE_LOCAL}/cross/${ARCH}

mkdir bin
mkdir usr
ln -sf /bin usr/bin
echo "Preparing libraries"
mkdir packages/libs
set +e
for pkg in packages/*
do
	for b in ${pkg}/bin/* ${pkg}/usr/bin/* ${pkg}/sbin/* ${pkg}/usr/sbin/*
	do
		if [ -f $b ]
		then 
			ln -sf ${KANAPI_BASE}/${b} bin
			file -i ${b} | grep application > /dev/null
			if [ "$?" = "0" ] ; then strip ${b} ; fi
		fi
	done
	for b in ${pkg}/lib/lib* ${pkg}/lib64/lib*
	do
		if [ -f $b ]
		then 
			ln -sf ${KANAPI_BASE}/${b} packages/libs
			file -i ${b} | grep x-sharedlib > /dev/null 
		   	if [ "$?" = "0" ] ; then strip ${b} ; fi
		fi
	done
done
for i in packages/gcc-${gcc_ver}/libexec/gcc/${ARCH}-kanapi-linux-gnu/${gcc_ver}/*
do		
	file -i ${i} | grep application > /dev/null
	if [ "$?" = "0" ] ; then strip ${i} ; fi
done
set -e
ln -svf bash bin/sh
ln -sf ${KANAPI_BASE_PACKAGES}/binutils-${binutils_ver}/${ARCH}-kanapi-linux-gnu/bin/* bin
echo "${KANAPI_VER} `date -R`" > sbs.version
mkdir kanapi_build
ln -sf /proc/mounts etc/mtab

cd ..
cp _start_chroot ${INITRD_DIR}
cp _start_build ${INITRD_DIR}
cp _start_bbs_build ${INITRD_DIR}
cp _test_build ${INITRD_DIR}
echo "Compressing image"
tar cJf sbs-${ARCH}.tar.xz sbs-${ARCH}
md5sum sbs-${ARCH}.tar.xz > sbs-${ARCH}.tar.xz.md5

