#!/bin/bash

#mount /proc
#mount /sys
#mount /dev/pts
#mount /dev/shm
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
#eval `dbus-launch --sh-syntax --exit-with-session`
#echo "DBUS_SESSION_BUS_PID=$DBUS_SESSION_BUS_PID"
echo "startuję $*"
tty

/bin/bash -c "$*"

#kill -9  $DBUS_SESSION_BUS_PID

#umount /dev/shm
#umount /dev/pts
#umount /sys
#umount /proc



